### ISSUE TITLE
Config changes

### ISSUE THREAD

**Issue by cwilson21** [binxio/terraform-google-privatebin#1]
I am fairly new to Terraform, but I am trying to set this up and want some different config values, and was wondering how I could change them without having to redo the module to fit what I need.

**Comment by mvanholsteijn** [comment]
Hi @cwilson21 ,I did not make an effort to create a highly configurable terraform module.  What things would you like to configure? The entire configuration is just 8 terraform resources; why not  copy the [main.tf](https://github.com/binxio/terraform-google-privatebin/blob/main/main.tf) and customise it to your liking?

**Comment by cwilson21** [comment]
> Hi @cwilson21 ,I did not make an effort to create a highly configurable terraform module. What things would you like to configure? The entire configuration is just 8 terraform resources; why not copy the [main.tf](https://github.com/binxio/terraform-google-privatebin/blob/main/main.tf) and customise it to your liking?

So I have what I need figured out, but why not specify "latest" in the secret key instead of a certain revision of a secret. I thought about breaking out this into what I need, but I mean I want to help make this easy to use for others in the future.  So as it stands I am creating a revision of the "secret" after it is created, but for it to see the latest config it needs to be set to "latest". 

```
      volumes {
        name = "config"
        secret {
          secret_name = element(reverse(split("/", google_secret_manager_secret.privatebin.name)), 0)
          items {
            key  = "latest"
            path = "conf.php"
          }
        }
      }
    }
  }
```
I think that would work.

**Comment by cwilson21** [comment]
In short, I would prefer help the open source world where a module already exists vs writing it to be what I need. Making something that is great for everyone to use vs just me has more value to me :)

**Comment by mvanholsteijn** [comment]
Hi @cwilson21 ,  The reason that I do not point to the "latest" version is that I like my IaC to be deterministic, so that when I read the code, I can predict the configuration.

For your use case, I can add the configuration file as a parameter to the module with the appropriate default value.  I will fix it for you in a sec.

**Comment by cwilson21** [comment]
@mvanholsteijn if that does not work out for you then I understand. I can respect wanting things to be deterministic like that. I was just trying to utilize something that already existed and make the changes I needed to the specific configuration file that is mounted as a secret. If I need to I can just go set it to use the latest myself in the cloud console.

**Comment by mvanholsteijn** [comment]
@cwilson21 hang in there for a little bit. I will make the privatebin configuration configurable

**Comment by mvanholsteijn** [comment]
@cwilson21 can you please see if https://github.com/binxio/terraform-google-privatebin/tree/main/examples/using_own_configuration does the trick for you?

**Comment by cwilson21** [comment]
@mvanholsteijn you sir are awesome! That is perfect, and makes it easy to manage the configuration instead of having it just be a HEREDOC in the middle of all the resources! I really appreciate it!

**Comment by mvanholsteijn** [comment]
you are welcome! glad you like it 🎉
